# Generated by Django 5.0.4 on 2024-04-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_categrory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
