# Generated by Django 4.2.11 on 2024-04-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='categrory',
            new_name='category',
        ),
    ]
