# Generated by Django 5.0.4 on 2024-05-01 13:36

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_rename_categrory_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.image_upload),
        ),
    ]
